In [33]:
import pandas as pd

In [34]:
ch = pd.read_csv(r'C:\Users\RahulK\Downloads\Machine Learning By Pranjal Sir\WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [35]:
ch.shape

(7043, 21)

In [36]:
ch.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [37]:
ch.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [38]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [39]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [40]:
from sklearn.preprocessing import LabelEncoder

In [41]:
le = LabelEncoder()

In [42]:
# We have to check which is nominal or ordinal data and cannot simply use label encoder for ordinal data
# We have to manually give value to the ordinal data

In [43]:
ch.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [49]:
ch.gender = le.fit_transform(ch.gender)
ch.Partner = le.fit_transform(ch.Partner)
ch.Dependents = le.fit_transform(ch.Dependents)
ch.PhoneService = le.fit_transform(ch.PhoneService)
ch.InternetService = le.fit_transform(ch.InternetService)
ch.DeviceProtection = le.fit_transform(ch.DeviceProtection)
ch.PaperlessBilling = le.fit_transform(ch.PaperlessBilling)
ch.PaymentMethod = le.fit_transform(ch.PaymentMethod)
ch.Churn.replace({'No': 0, 'Yes': 1}, inplace= True) # just to make sure that 'yes' get 1 and 'no' get 0
# Above are nominal columns

# Below is ordinals
ch.Contract.replace({'Month-to-month': 0, 'One year': 1, 'Two year': 2}, inplace= True)
ch.MultipleLines.replace({'No phone service': 0, 'No': 1, 'Yes': 2}, inplace= True)
ch.TechSupport.replace({'No internet service': 0, 'No': 1, 'Yes': 2}, inplace= True)
ch.OnlineSecurity.replace({'No internet service': 0, 'No': 1, 'Yes': 2}, inplace= True)
ch.StreamingTV.replace({'No internet service': 0, 'No': 1, 'Yes': 2}, inplace= True)
ch.StreamingMovies.replace({'No internet service': 0, 'No': 1, 'Yes': 2}, inplace= True)
ch.OnlineBackup.replace({'No internet service': 0, 'No': 1, 'Yes': 2}, inplace= True)

In [25]:
ch.Contract.value_counts()

Month-to-month    3875
Two year          1695
One year          1473
Name: Contract, dtype: int64

In [26]:
ch.Churn.value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [27]:
ch.MultipleLines.value_counts()

No                  3390
Yes                 2971
No phone service     682
Name: MultipleLines, dtype: int64

In [45]:
ch.OnlineBackup.value_counts()

No                     3088
Yes                    2429
No internet service    1526
Name: OnlineBackup, dtype: int64

In [46]:
ch.OnlineSecurity.value_counts()

No                     3498
Yes                    2019
No internet service    1526
Name: OnlineSecurity, dtype: int64

In [47]:
ch.StreamingMovies.value_counts()

No                     2785
Yes                    2732
No internet service    1526
Name: StreamingMovies, dtype: int64

In [48]:
ch.StreamingTV.value_counts()

No                     2810
Yes                    2707
No internet service    1526
Name: StreamingTV, dtype: int64

In [44]:
ch.TechSupport.value_counts()

No                     3473
Yes                    2044
No internet service    1526
Name: TechSupport, dtype: int64

In [50]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   int32  
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   int32  
 4   Dependents        7043 non-null   int32  
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   int32  
 7   MultipleLines     7043 non-null   int64  
 8   InternetService   7043 non-null   int32  
 9   OnlineSecurity    7043 non-null   int64  
 10  OnlineBackup      7043 non-null   int64  
 11  DeviceProtection  7043 non-null   int32  
 12  TechSupport       7043 non-null   int64  
 13  StreamingTV       7043 non-null   int64  
 14  StreamingMovies   7043 non-null   int64  
 15  Contract          7043 non-null   int64  
 16  PaperlessBilling  7043 non-null   int32  


In [51]:
# TotalCharger column is an object and we found some blank values as well
# so we need to convert blank into nulls and then convert data type to float


import numpy as np

In [52]:
ch.TotalCharges.replace({" ": np.nan}, inplace= True)

In [53]:
ch.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [54]:
# We have 11 null values in the TotalCharges column now
# we will convert data type to float first and then will replace the null

ch.TotalCharges = ch.TotalCharges.astype('float')

In [55]:
ch.TotalCharges.fillna(ch.TotalCharges.mean(), inplace= True)

In [56]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   int32  
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   int32  
 4   Dependents        7043 non-null   int32  
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   int32  
 7   MultipleLines     7043 non-null   int64  
 8   InternetService   7043 non-null   int32  
 9   OnlineSecurity    7043 non-null   int64  
 10  OnlineBackup      7043 non-null   int64  
 11  DeviceProtection  7043 non-null   int32  
 12  TechSupport       7043 non-null   int64  
 13  StreamingTV       7043 non-null   int64  
 14  StreamingMovies   7043 non-null   int64  
 15  Contract          7043 non-null   int64  
 16  PaperlessBilling  7043 non-null   int32  


In [59]:
ch1 =ch

In [62]:
ch = ch.drop(['customerID'], axis= 1)

In [65]:
from sklearn.model_selection import train_test_split

In [69]:
ch_train, ch_test = train_test_split(ch, test_size= .2)

In [70]:
ch_train.shape

(5634, 20)

In [71]:
ch_test.shape

(1409, 20)

In [95]:
ch_train_x = ch_train.iloc[ : , 0:-1 ]
ch_train_y = ch_train.iloc[:, -1]

ch_test_x = ch_test.iloc[ : , 0:-1 ]
ch_test_y = ch_test.iloc[:, -1]

In [96]:
from sklearn.linear_model import LogisticRegression

In [97]:
logch = LogisticRegression()

In [98]:
logch.fit(ch_train_x, ch_train_y)

C:\Users\RahulK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [99]:
pred_ch_test = logch.predict(ch_test_x)

In [100]:
from sklearn.metrics import confusion_matrix

In [101]:
tab_ch = confusion_matrix(ch_test_y,pred_ch_test)

In [102]:
tab_ch

array([[781, 244],
       [ 98, 286]], dtype=int64)

In [89]:
a = tab_ch

In [80]:
Accuracy = tab_ch.diagonal().sum()/ tab_ch.sum()
Accuracy

0.7906316536550745

In [85]:
FPR = tab_ch[0,1]/tab_ch[0].sum()
FPR

0.1024390243902439

In [86]:
from sklearn.metrics import recall_score

TPR = recall_score(ch_test_y, pred_ch_test)
TPR

0.5052083333333334

In [87]:
from sklearn.metrics import precision_score

Precision = precision_score(ch_test_y, pred_ch_test)
Precision

# Here Precision will be the important factor as we are targeting class 1
#  and the company agrees that they cannot focus the entire customer as they have huge customers
# So, Precision will be considered instead of TPR

0.6488294314381271

In [88]:
# Oversampling is done after sampling and will be done only on the train data

# That is after this --> 'ch_train, ch_test = train_test_split(ch, test_size= .2)'

In [90]:
ch_train.Churn.value_counts()

0    4149
1    1485
Name: Churn, dtype: int64

In [91]:
rec_for_class1 = ch_train[ch_train.Churn == 1]

rec_for_class1.shape

(1485, 20)

In [93]:
ch_train = pd.concat([ch_train, rec_for_class1])

# Adding duplicate values in the train data for class 1, oversampling

In [94]:
ch_train.Churn.value_counts()

0    4149
1    2970
Name: Churn, dtype: int64

In [103]:
# Now execute from
# ch_train_x = ch_train.iloc[ : , 0:-1 ]


In [104]:
# Before oversampling our confusion matrix was

a

array([[920, 105],
       [190, 194]], dtype=int64)

In [105]:
# after oversampling our confusion matrix became

tab_ch

array([[781, 244],
       [ 98, 286]], dtype=int64)

In [107]:
# As you can see our Precison has gone down from before

Precision = precision_score(ch_test_y, pred_ch_test)
Precision

0.539622641509434