In [1]:
import pandas as pd
import numpy as np

In [2]:
cr = pd.read_csv(r'C:\Users\RahulK\Downloads\Machine Learning By Pranjal Sir\Supervised\AdaBoost\CreditRisk.csv')

In [3]:
cr.head()

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No         0.0      Graduate            No   
1  LP001003   Male     Yes         1.0      Graduate            No   
2  LP001005   Male     Yes         0.0      Graduate           Yes   
3  LP001006   Male     Yes         0.0  Not Graduate            No   
4  LP001008   Male      No         0.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
cr.Gender.fillna('Male', inplace= True)
cr.Married.fillna('No', inplace= True)
cr.Dependents.fillna(0, inplace= True)
cr.Self_Employed.fillna('Yes', inplace= True)
cr.LoanAmount.fillna(cr.LoanAmount.mean(), inplace= True)
cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.mean(), inplace= True)
cr.Credit_History.fillna(1, inplace= True)

In [5]:
cr = cr.iloc[:,1::]

In [6]:
cr.Gender.replace({'Female': 0, 'Male': 1}, inplace= True)
cr.Married.replace({'No': 0, 'Yes': 1}, inplace= True)
cr.Education.replace({'Not Graduate': 0, 'Graduate': 1}, inplace= True)
cr.Self_Employed.replace({'No': 0, 'Yes': 1}, inplace= True)
cr.Property_Area.replace({'Rural': 3, 'Semiurban': 1, 'Urban': 2}, inplace= True)
cr.Loan_Status.replace({'N': 0, 'Y': 1}, inplace= True)

In [7]:
cr.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0         0.0          1              0             5849   
1       1        1         1.0          1              0             4583   
2       1        1         0.0          1              1             3000   
3       1        1         0.0          0              0             2583   
4       1        0         0.0          1              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0   142.51153             360.0             1.0   
1             1508.0   128.00000             360.0             1.0   
2                0.0    66.00000             360.0             1.0   
3             2358.0   120.00000             360.0             1.0   
4                0.0   141.00000             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              3            0  
2              2            1  
3              2            1  
4              2            1

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
cr_train, cr_test = train_test_split(cr, test_size=.2)

In [10]:
cr_train_x = cr_train.iloc[:, 0:-1]
cr_train_y = cr_train.iloc[:,-1]

cr_test_x = cr_test.iloc[:, 0:-1]
cr_test_y = cr_test.iloc[:,-1]

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
from sklearn.ensemble import AdaBoostClassifier

In [13]:
dt = DecisionTreeClassifier()

In [14]:
abc_cr = AdaBoostClassifier(dt, n_estimators= 10)

In [16]:
abc_cr.fit(cr_train_x, cr_train_y)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=10)

In [17]:
pred = abc_cr.predict(cr_test_x)

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [19]:
tab = confusion_matrix(cr_test_y, pred)
tab

array([[ 26,  16],
       [ 21, 134]], dtype=int64)

In [20]:
dt.fit(cr_train_x, cr_train_y)

DecisionTreeClassifier()

In [22]:
pred_dt = dt.predict(cr_test_x)

In [23]:
tab_dt = confusion_matrix(cr_test_y, pred_dt)
tab_dt

array([[ 26,  16],
       [ 22, 133]], dtype=int64)

In [31]:
Accuracy_dt = accuracy_score(cr_test_y, pred_dt)*100
Accuracy_dt

80.71065989847716

In [24]:
dt = DecisionTreeClassifier(criterion= 'entropy',max_depth= 5, min_samples_split= 75)

In [25]:
abc_cr = AdaBoostClassifier(dt, n_estimators= 10)

In [26]:
abc_cr.fit(cr_train_x, cr_train_y)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',
                                                         max_depth=5,
                                                         min_samples_split=75),
                   n_estimators=10)

In [27]:
pred = abc_cr.predict(cr_test_x)

In [28]:
tab = confusion_matrix(cr_test_y, pred)
tab

array([[ 27,  15],
       [ 14, 141]], dtype=int64)

In [33]:
Accuracy = accuracy_score(cr_test_y, pred)*100
Accuracy

85.27918781725889

In [34]:
from sklearn.ensemble import ExtraTreesClassifier

In [35]:
etc = ExtraTreesClassifier()

In [36]:
etc.fit(cr_train_x, cr_train_y)

ExtraTreesClassifier()

In [37]:
pred_etc = etc.predict(cr_test_x)

In [38]:
tab_etc = confusion_matrix(cr_test_y, pred_etc)
tab_etc

array([[ 24,  18],
       [  8, 147]], dtype=int64)

In [39]:
Accuracy_etc = accuracy_score(cr_test_y, pred_etc)*100
Accuracy_etc

86.80203045685279

In [40]:
etc = ExtraTreesClassifier(criterion= 'entropy')
etc.fit(cr_train_x, cr_train_y)

ExtraTreesClassifier(criterion='entropy')

In [41]:
pred_etc = etc.predict(cr_test_x)
tab_etc = confusion_matrix(cr_test_y, pred_etc)
tab_etc

array([[ 25,  17],
       [  7, 148]], dtype=int64)

In [42]:
Accuracy_etc = accuracy_score(cr_test_y, pred_etc)*100
Accuracy_etc

87.81725888324873