In [16]:
import pandas as pd
import numpy as np

In [17]:
mp = pd.read_csv(r'C:\Users\RahulK\Downloads\Machine Learning By Pranjal Sir\Supervised\HyperParameter Tuning\trainRF.csv')

In [18]:
mp.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
mp_train, mp_test = train_test_split(mp, test_size= .2)

In [21]:
mp_train_x = mp_train.iloc[:,0:-1]
mp_train_y = mp_train.iloc[:, -1]

mp_test_x = mp_test.iloc[:,0:-1]
mp_test_y = mp_test.iloc[:, -1]

In [22]:
from sklearn.naive_bayes import MultinomialNB

In [23]:
nb_mp = MultinomialNB()

In [24]:
nb_mp.fit(mp_train_x, mp_train_y)

MultinomialNB()

In [25]:
pred = nb_mp.predict(mp_test_x)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
tab_mp = confusion_matrix(mp_test_y, pred)
tab_mp


array([[68, 19,  5,  0],
       [22, 41, 25, 17],
       [ 5, 27, 33, 43],
       [ 0, 10, 17, 68]], dtype=int64)

In [28]:
Accuracy = accuracy_score(mp_test_y, pred)*100
Accuracy

52.5

# Hyper Parameter Tuning

In [29]:
from sklearn.model_selection import GridSearchCV

In [30]:
search_dict = {'criterion' : ['entropy', 'gini'],
              'max_depth': [5,6,7,8],
              'min_samples_split': [50,75,100,125]}

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
dt =DecisionTreeClassifier()

In [33]:
grid = GridSearchCV(dt, param_grid= search_dict)

In [34]:
grid.fit(mp_train_x, mp_train_y)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': [5, 6, 7, 8],
                         'min_samples_split': [50, 75, 100, 125]})

In [35]:
grid.best_params_

# Will give the best parameters

{'criterion': 'entropy', 'max_depth': 6, 'min_samples_split': 50}

In [36]:
pred_with_best_parameters = grid.predict(mp_test_x)

In [37]:
tab_best = confusion_matrix(mp_test_y, pred_with_best_parameters)
tab_best

array([[78, 14,  0,  0],
       [ 8, 82, 15,  0],
       [ 0,  6, 85, 17],
       [ 0,  0, 11, 84]], dtype=int64)

In [39]:
Accuracy_best = accuracy_score(mp_test_y, pred_with_best_parameters)*100
Accuracy_best

82.25

In [40]:
# Example of RandomForest

In [41]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [58]:
search_dict_rfc = {'criterion' : ['entropy', 'gini'],
              'n_estimators': [100,110,115,120,125]}

In [59]:
grid = GridSearchCV(rfc, param_grid= search_dict_rfc)

In [60]:
grid.fit(mp_train_x, mp_train_y)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['entropy', 'gini'],
                         'n_estimators': [100, 110, 115, 120, 125]})

In [61]:
grid.best_params_

{'criterion': 'entropy', 'n_estimators': 120}

In [62]:
pred_rfc = grid.predict(mp_test_x)

In [63]:
tab_rfc = confusion_matrix(mp_test_y, pred_rfc)
tab_rfc

array([[85,  7,  0,  0],
       [ 7, 89,  9,  0],
       [ 0, 13, 85, 10],
       [ 0,  0,  8, 87]], dtype=int64)

In [64]:
Accuracy_rfc = accuracy_score(mp_test_y, pred_rfc)*100
Accuracy_rfc

86.5